// Copyright 2025 The XLS Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "xls/contrib/mlir/transforms/linalg/dslxgen.h"

#include <algorithm>
#include <climits>
#include <cstdint>
#include <sstream>
#include <string>
#include <vector>

#include "absl/container/flat_hash_map.h"
#include "absl/strings/str_cat.h"
#include "absl/strings/str_join.h"
#include "linalg_types.h"
#include "xls/contrib/mlir/transforms/linalg/dslx_types.h"
#include "xls/contrib/mlir/transforms/linalg/linalg_config.h"
#include "xls/contrib/mlir/transforms/linalg/linalg_eval.h"
#include "xls/contrib/mlir/transforms/linalg/linalg_types.h"

namespace mlir::xls {

DslxGen::DslxGen() : OutT_() {}

FailureOr<std::string> DslxGen::GenerateDslxCode(
    const LinalgEvalResults& eval_results, const Schedule& schedule) {
  if (failed(InitStream()) || failed(EmitHeader(eval_results.reduction_op)) ||
      failed(EmitInits(eval_results, schedule)) ||
      failed(EmitSignature(eval_results)) ||
      failed(EmitLoopBody(eval_results, schedule))) {
    return failure();
  }

  return dslx_stream_.str();
}

LogicalResult DslxGen::InitStream() {
  dslx_stream_.str("");
  dslx_stream_.clear();
  return success();
}

LogicalResult DslxGen::EmitHeader(OpKind reduction_op) {
  if (failed(EmitFileHeader()) || failed(EmitFeatureFlag()) ||
      failed(EmitImports()) || failed(EmitF32TypeAliases()) ||
      failed(EmitConstants(reduction_op))) {
    return failure();
  }
  return success();
}

LogicalResult DslxGen::EmitFileHeader() {
  dslx_stream_ << "// Generated by dslxgen from MLIR Linalg operation\n"
               << "// DO NOT EDIT - This file is auto-generated\n\n";
  return success();
}

LogicalResult DslxGen::EmitFeatureFlag() {
  dslx_stream_ << "#![feature(type_inference_v2)]\n\n";
  return success();
}

LogicalResult DslxGen::EmitImports() {
  dslx_stream_ << "import float32;\n\n";
  return success();
}

LogicalResult DslxGen::EmitF32TypeAliases() {
  dslx_stream_ << "type F32 = float32::F32;\n\n";
  return success();
}

LogicalResult DslxGen::EmitConstants(OpKind reduction_op) {
  switch (reduction_op) {
    case OpKind::kAddF:
    case OpKind::kSubF:
      dslx_stream_ << "const F32_ZERO = float32::zero(false);\n";
      break;
    case OpKind::kMulF:
      dslx_stream_ << "const F32_ONE = float32::one(false);\n";
      break;
    default:
      dslx_stream_ << "const F32_ZERO = float32::zero(false);\n";
      dslx_stream_ << "const F32_ONE = float32::one(false);\n";
      break;
  }
  return success();
}

LogicalResult DslxGen::EmitInits(const LinalgEvalResults& eval_results,
                                 const Schedule& schedule) {
  return success();
}

LogicalResult DslxGen::EmitSignature(const LinalgEvalResults& eval_results) {
  if (failed(EmitFunctionName(eval_results.function_name)) ||
      failed(EmitInputParameters(eval_results.linalg.operands,
                                 eval_results.shapes.first)) ||
      failed(EmitReturnType(eval_results.linalg.operands,
                            eval_results.shapes.second))) {
    return failure();
  }
  return success();
}

LogicalResult DslxGen::EmitLoopBody(const LinalgEvalResults& eval_results,
                                    const Schedule& schedule) {
  auto statements = BuildBodyStatements(eval_results, schedule);
  if (failed(statements)) {
    return failure();
  }

  if (failed(EmitStatements(*statements))) {
    return failure();
  }

  dslx_stream_ << "}\n";
  return success();
}

LogicalResult DslxGen::EmitFunctionName(const std::string& function_name) {
  dslx_stream_ << "fn " << function_name << "(";
  return success();
}

LogicalResult DslxGen::EmitInputParameters(
    const std::vector<Operand>& operands,
    const std::vector<InputShapeInfo>& input_shapes) {
  std::vector<std::string> params;
  size_t input_shape_index = 0;
  for (const auto& operand : operands) {
    if (!operand.is_output) {
      std::string param_type;
      if (input_shape_index < input_shapes.size()) {
        auto derived_type =
            BuildParameterTypeFromDerived(input_shapes[input_shape_index]);
        if (failed(derived_type)) {
          return failure();
        }
        param_type = *derived_type;
        input_shape_index++;
      } else {
        auto fallback_type = BuildParameterType(operand);
        if (failed(fallback_type)) {
          return failure();
        }
        param_type = *fallback_type;
      }
      params.push_back(operand.name + ": " + param_type);
    }
  }
  dslx_stream_ << absl::StrJoin(params, ", ");
  return success();
}

LogicalResult DslxGen::EmitReturnType(
    const std::vector<Operand>& operands,
    const std::vector<OutputShapeInfo>& output_shapes) {
  std::vector<std::string> output_types;
  size_t output_idx = 0;
  for (const auto& operand : operands) {
    if (operand.is_output) {
      if (output_idx < output_shapes.size()) {
        auto output_type =
            BuildDslxTypeFromSizeExprs(output_shapes[output_idx].out_shape);
        if (succeeded(output_type)) {
          output_types.push_back(*output_type);
        } else {
          return failure();
        }
        output_idx++;
      }
    }
  }

  if (output_types.empty()) {
    dslx_stream_ << ") -> () {\n";
  } else if (output_types.size() == 1) {
    dslx_stream_ << ") -> " << output_types[0] << " {\n";
  } else {
    dslx_stream_ << ") -> (" << absl::StrJoin(output_types, ", ") << ") {\n";
  }
  return success();
}

FailureOr<std::string> DslxGen::BuildParameterType(const Operand& operand) {
  std::vector<std::string> dims;
  for (auto it = operand.type.shape.rbegin(); it != operand.type.shape.rend();
       ++it) {
    dims.push_back(std::to_string(*it));
  }
  return absl::StrCat("F32[", absl::StrJoin(dims, "]["), "]");
}

FailureOr<std::string> DslxGen::BuildDslxTypeFromSizeExprs(
    const std::vector<SizeExpr>& dimensions) {
  std::vector<std::string> dims;
  for (const auto& dim : dimensions) {
    if (dim.isConstant()) {
      dims.push_back(std::to_string(dim.getConstant()));
    } else {
      dims.push_back(dim.getSymbolic());
    }
  }

  if (dims.empty()) {
    return std::string("F32");
  }

  // Use dimensions in original order - the mapping system handles XLS array
  // representation
  return absl::StrCat("F32[", absl::StrJoin(dims, "]["), "]");
}

FailureOr<std::string> DslxGen::BuildParameterTypeFromDerived(
    const InputShapeInfo& input_shape) {
  return BuildDslxTypeFromSizeExprs(input_shape.dslx_shape);
}

FailureOr<std::string> DslxGen::BuildTypedNestedPattern(
    const std::vector<std::string>& dims, const std::string& scalar_value, const std::string& macro_name) {
  if (dims.empty()) return scalar_value;

  std::string result = macro_name + "!<F32";
  for (const auto& dim : dims) {
    result += "[" + dim + "]";
  }
  result += ">()";

  return result;
}

FailureOr<std::string> DslxGen::BuildTypedNestedZeroPattern(
    const std::vector<std::string>& dims) {
  return BuildTypedNestedPattern(dims, "F32_ZERO", "zero");
}

int64_t DslxGen::GetLoopBoundFromSchedule(const Schedule& schedule,
                                          int logical_dim) {
  for (const auto& loop : schedule.bands[0].loops) {
    if (loop.dim == logical_dim) {
      return loop.end;
    }
  }
  return 1;
}

int DslxGen::CalculateLoopBitwidth(int64_t bound) {
  if (bound <= 0) {
    return 32;
  }

  int64_t max_value = bound - 1;

  if (max_value <= UINT32_MAX) {
    return 32;
  } else {
    return 64;
  }
}

DslxStmt BuildReduction(int r_pos, const LinalgEvalResults& eval_results,
                        const std::vector<int>& P, const std::vector<int>& R,
                        const Schedule& schedule, int indent);

DslxStmt BuildParallel(int p_pos, const LinalgEvalResults& eval_results,
                       const std::vector<int>& P, const std::vector<int>& R,
                       const Schedule& schedule, int indent,
                       const std::string& OutT);

FailureOr<std::vector<DslxStmt>> DslxGen::BuildBodyStatements(
    const LinalgEvalResults& eval_results, const Schedule& schedule) {
  std::vector<DslxStmt> statements;
  const auto& [P, R] = schedule.parallel_and_reduction_dims;

  if (!eval_results.shapes.second.empty()) {
    auto output_type_result =
        BuildDslxTypeFromSizeExprs(eval_results.shapes.second[0].out_shape);
    if (failed(output_type_result)) {
      return failure();
    }
    OutT_ = std::move(*output_type_result);
  }

  if (!P.empty()) {
    auto parallel_stmt_result =
        BuildParallel(0, eval_results, P, R, schedule, 2, OutT_);
    if (failed(parallel_stmt_result)) {
      return failure();
    }
    statements.push_back(std::move(*parallel_stmt_result));
  } else if (!R.empty()) {
    auto reduction_stmt_result =
        BuildReduction(0, eval_results, P, R, schedule, 2);
    if (failed(reduction_stmt_result)) {
      return failure();
    }
    statements.push_back(std::move(*reduction_stmt_result));
  } else {
    statements.push_back(DslxStmt::MakeLet("result", "F32", "F32_ZERO"));
  }

  return statements;
}

FailureOr<DslxStmt> DslxGen::BuildParallel(int p_pos,
                                const LinalgEvalResults& eval_results,
                                const std::vector<int>& P,
                                const std::vector<int>& R,
                                const Schedule& schedule, int indent,
                                const std::string& OutT) {
  const int mP = static_cast<int>(P.size());
  std::string dim_name = "p" + std::to_string(p_pos);

  auto a = MakeParallelAcc(p_pos, mP, P, schedule);
  if (failed(a)) {
    return failure();
  }
  Accumulator acc = std::move(*a);

  int64_t bound = GetLoopBoundFromSchedule(schedule, P[p_pos]);
  std::vector<DslxStmt> body_stmts;

  if (p_pos == mP - 1) {
    if (!R.empty()) {
      auto reduction_stmt_result =
          BuildReduction(0, eval_results, P, R, schedule, indent + 2);
      if (failed(reduction_stmt_result)) {
        return failure();
      }
      DslxStmt reduction_stmt = std::move(*reduction_stmt_result);
      reduction_stmt.for_loop.name = "red0_final";
      body_stmts.push_back(std::move(reduction_stmt));
    }
  } else {
    std::string child_name =
        (p_pos == mP - 2) ? "row_final"
                          : "tile" + std::to_string(p_pos + 1) + "_final";
    auto next_parallel_result = BuildParallel(p_pos + 1, eval_results, P, R,
                                           schedule, indent + 2, OutT);
    if (failed(next_parallel_result)) {
      return failure();
    }
    DslxStmt next_parallel = std::move(*next_parallel_result);
    next_parallel.for_loop.name = child_name;
    body_stmts.push_back(std::move(next_parallel));
  }

  std::string acc_name =
      (mP >= 2 && p_pos == mP - 1) ? "row" : "acc" + std::to_string(p_pos);
  std::string iv_name = "p" + std::to_string(p_pos);
  std::string update_value;

  if (p_pos == mP - 1) {
    update_value = "red0_final";
  } else if (p_pos == mP - 2) {
    update_value = "row_final";
  } else {
    update_value = "tile" + std::to_string(p_pos + 1) + "_final";
  }

  body_stmts.push_back(DslxStmt::MakeUpdate(acc_name, iv_name, update_value));

  return DslxStmt::MakeFor(dim_name, acc.name, acc.type, 0, bound,
                           std::move(body_stmts), "", acc.init);
}

FailureOr<DslxStmt> DslxGen::BuildReduction(int r_pos,
                                 const LinalgEvalResults& eval_results,
                                 const std::vector<int>& P,
                                 const std::vector<int>& R,
                                 const Schedule& schedule, int indent) {
  const int mR = static_cast<int>(R.size());
  std::string dim_name = "r" + std::to_string(r_pos);

  auto r = MakeReductionAcc(r_pos, mR, eval_results);
  if (failed(r)) {
    return failure();
  }
  Accumulator acc = std::move(*r);

  int64_t bound = GetLoopBoundFromSchedule(schedule, R[r_pos]);
  std::vector<DslxStmt> body_stmts;

  if (r_pos == mR - 1) {
    auto expression_result =
        BuildRegionExpression(eval_results.linalg.region,
                              eval_results.linalg.operands, acc.name, schedule);
    if (succeeded(expression_result)) {
      auto [let_stmts, final_expr] = std::move(*expression_result);
      body_stmts.insert(body_stmts.end(),
                        std::make_move_iterator(let_stmts.begin()),
                        std::make_move_iterator(let_stmts.end()));

      return DslxStmt::MakeFor(dim_name, acc.name, acc.type, 0, bound,
                               std::move(body_stmts), final_expr, acc.init);
    }

    return DslxStmt::MakeFor(dim_name, acc.name, acc.type, 0, bound,
                             std::move(body_stmts), "", acc.init);
  } else {
    auto next_reduction_result =
        BuildReduction(r_pos + 1, eval_results, P, R, schedule, indent + 2);
    if (failed(next_reduction_result)) {
      return failure();
    }
    DslxStmt next_reduction = std::move(*next_reduction_result);
    next_reduction.for_loop.name = "red" + std::to_string(r_pos + 1) + "_final";
    body_stmts.push_back(std::move(next_reduction));
    return DslxStmt::MakeFor(
        dim_name, acc.name, acc.type, 0, bound, std::move(body_stmts),
        "red" + std::to_string(r_pos + 1) + "_final", acc.init);
  }
}

LogicalResult DslxGen::EmitStatements(const std::vector<DslxStmt>& stmts,
                                      int indent) {
  for (const auto& stmt : stmts) {
    if (failed(EmitStatement(stmt, indent))) {
      return failure();
    }
  }
  return success();
}

LogicalResult DslxGen::EmitStatement(const DslxStmt& stmt, int indent) {
  std::string indent_str(indent, ' ');

  switch (stmt.kind) {
    case DslxStmt::kLet: {
      const auto& let = stmt.let;
      dslx_stream_ << indent_str << "let " << let.name << ": " << let.type
                   << " = " << let.rhs << ";\n";
      break;
    }
    case DslxStmt::kFor: {
      const auto& for_loop = stmt.for_loop;
      int bitwidth = CalculateLoopBitwidth(for_loop.end);

      if (for_loop.name.has_value()) {
        dslx_stream_ << indent_str << "let " << for_loop.name.value() << " = ";
      } else {
        dslx_stream_ << indent_str;
      }

      dslx_stream_ << "for (" << for_loop.dim_name << ", " << for_loop.acc
                   << "): (u" << bitwidth << ", " << for_loop.acc_type
                   << ") in u" << bitwidth << ":" << for_loop.begin << "..u"
                   << bitwidth << ":" << for_loop.end << " {\n";

      if (failed(EmitStatements(for_loop.body_stmts, indent + 4))) {
        return failure();
      }

      if (!for_loop.body_expr.empty()) {
        dslx_stream_ << indent_str << "    " << for_loop.body_expr << "\n";
      }
      dslx_stream_ << indent_str << "  }";
      if (!for_loop.seed.empty()) {
        dslx_stream_ << " (" << for_loop.seed << ")";
      }

      if (for_loop.name.has_value()) {
        dslx_stream_ << ";";
      }
      dslx_stream_ << "\n";
      break;
    }
    case DslxStmt::kUpdate: {
      const auto& update = stmt.update;
      dslx_stream_ << indent_str << "update(" << update.array << ", "
                   << update.index << ", " << update.new_value << ")\n";
      break;
    }
  }
  return success();
}

FailureOr<Accumulator> DslxGen::MakeParallelAcc(int p_pos, int mP,
                                                const std::vector<int>& P,
                                                const Schedule& schedule) {
  if (mP == 0) {
    return failure();
  }

  if (p_pos < 0 || p_pos >= mP) {
    return failure();
  }

  std::string name, type, init;

  if (mP == 1) {
    name = "acc0";
    type = OutT_.empty() ? "F32" : OutT_;
  } else if (p_pos == 0) {
    name = "acc0";
    type = OutT_.empty() ? "F32" : OutT_;
  } else if (p_pos == mP - 1) {
    name = "row";

    type = MakeRowTWithMapping(schedule);
  } else {
    name = "acc" + std::to_string(p_pos);

    type = MakeSuffixTypeWithMapping(p_pos, schedule);
  }

  if (type == "F32") {
    init = "F32_ZERO";
  } else {
    std::vector<std::string> dims;
    std::string temp = type;
    size_t pos = temp.find("[");
    while (pos != std::string::npos) {
      size_t end_pos = temp.find("]", pos);
      if (end_pos != std::string::npos) {
        dims.push_back(temp.substr(pos + 1, end_pos - pos - 1));
        pos = temp.find("[", end_pos);
      } else {
        break;
      }
    }

    auto pattern = BuildTypedNestedZeroPattern(dims);
    if (failed(pattern)) {
      return failure();
    }

    init = std::move(*pattern);
  }

  return Accumulator(std::move(name), std::move(type), std::move(init));
}

FailureOr<Accumulator> DslxGen::MakeReductionAcc(
    int r_pos, int mR, const LinalgEvalResults& eval_results) {
  // Use the actual reduction operation from evaluation results
  std::string name = "red" + std::to_string(r_pos);
  std::string type = "F32";  // Reduction accumulators are always scalar
  std::string init;
  
  switch (eval_results.reduction_op) {
    case OpKind::kAddF:
    case OpKind::kSubF:
      init = "F32_ZERO";
      break;
    case OpKind::kMulF:
      init = "F32_ONE";
      break;
    default:
      return failure();
  }
  
  return Accumulator(std::move(name), std::move(type), std::move(init));
}

// Build tensor indexing using dimension mapping
std::string DslxGen::BuildTensorIndexingWithMapping(const Operand& operand,
                                                    const Schedule& schedule) {
  std::string base_name = operand.name;

  // Collect all indices first, then reverse them for XLS array representation
  std::vector<std::string> indices;

  for (const auto& affine_expr : operand.map.results) {
    if (affine_expr.kind == AffineExpr::kVar) {
      int logical_dim = affine_expr.var;

      // Use the new mapping instead of searching through P/R arrays
      auto it = schedule.mlir_dim_to_loop_var.find(logical_dim);
      if (it != schedule.mlir_dim_to_loop_var.end()) {
        indices.push_back(it->second);
      } else {
        indices.push_back("0");  // fallback
      }
    } else if (affine_expr.kind == AffineExpr::kConst0) {
      indices.push_back("0");
    }
  }

  // Reverse indices for XLS array representation
  // MLIR: tensor<4x5x6x7x8xf32> → XLS: F32[8][7][6][5][4]
  // So MLIR indexing [p][q][r][k][l] becomes XLS indexing [l][k][r][q][p]
  std::reverse(indices.begin(), indices.end());

  // Build the final indexing expression
  for (const auto& index : indices) {
    base_name += "[" + index + "]";
  }

  return base_name;
}

// NEW: MakeSuffixType using dimension mapping
std::string DslxGen::MakeSuffixTypeWithMapping(int k,
                                               const Schedule& schedule) {
  std::vector<SizeExpr> suffix_dims;

  // Use the mapping to get dimensions in the correct order
  // We need to get all parallel dimensions from position k onwards
  const auto& [P, R] = schedule.parallel_and_reduction_dims;

  // Build suffix dimensions using the mapping
  for (int j = static_cast<int>(P.size()) - 1; j >= k; --j) {
    int logical_dim = P[j];
    suffix_dims.push_back(
        SizeExpr(GetLoopBoundFromSchedule(schedule, logical_dim)));
  }

  auto result = BuildDslxTypeFromSizeExprs(suffix_dims);
  return succeeded(result) ? *result : "F32";
}

// NEW: MakeRowT using dimension mapping
std::string DslxGen::MakeRowTWithMapping(const Schedule& schedule) {
  if (schedule.row_len > 0) {
    // Use the mapping to get the last parallel dimension (the one we're looping
    // over)
    const auto& [P, R] = schedule.parallel_and_reduction_dims;
    if (!P.empty()) {
      int logical_dim =
          P.back();  // Last parallel dimension (the one we're looping over)
      int64_t row_size = GetLoopBoundFromSchedule(schedule, logical_dim);
      return "F32[" + std::to_string(row_size) + "]";
    }
  }
  return "F32";
}

FailureOr<std::pair<std::vector<DslxStmt>, std::string>>
DslxGen::BuildRegionExpression(const Region& region,
                               const std::vector<Operand>& operands,
                               const std::string& accumulator_name,
                               const Schedule& schedule) {
  if (region.ops.empty()) {
    return failure();
  }

  absl::flat_hash_map<ValueId, std::string> value_map;
  std::vector<DslxStmt> let_statements;

  for (size_t i = 0; i < region.args.size() && i < operands.size(); ++i) {
    const auto& operand = operands[i];
    if (operand.is_output) {
      value_map[region.args[i]] = accumulator_name;
    } else {
      std::string indexed_name =
          BuildTensorIndexingWithMapping(operand, schedule);
      value_map[region.args[i]] = indexed_name;
    }
  }

  for (const auto& op : region.ops) {
    std::string result_name = "val" + std::to_string(op.result.id);
    std::string expr;

    switch (op.kind) {
      case OpKind::kAddF:
        if (op.inputs.size() >= 2) {
          expr = "float32::add(" + value_map[op.inputs[0]] + ", " +
                 value_map[op.inputs[1]] + ")";
        }
        break;
      case OpKind::kMulF:
        if (op.inputs.size() >= 2) {
          expr = "float32::mul(" + value_map[op.inputs[0]] + ", " +
                 value_map[op.inputs[1]] + ")";
        }
        break;
      case OpKind::kSubF:
        if (op.inputs.size() >= 2) {
          expr = "float32::sub(" + value_map[op.inputs[0]] + ", " +
                 value_map[op.inputs[1]] + ")";
        }
        break;
      case OpKind::kDivF:
        if (op.inputs.size() >= 2) {
          expr = "float32::div(" + value_map[op.inputs[0]] + ", " +
                 value_map[op.inputs[1]] + ")";
        }
        break;
      case OpKind::kMaxF:
        if (op.inputs.size() >= 2) {
          expr = "float32::max(" + value_map[op.inputs[0]] + ", " +
                 value_map[op.inputs[1]] + ")";
        }
        break;
      case OpKind::kMinF:
        if (op.inputs.size() >= 2) {
          expr = "float32::min(" + value_map[op.inputs[0]] + ", " +
                 value_map[op.inputs[1]] + ")";
        }
        break;
      case OpKind::kConstF32: {
        uint32_t bits = *reinterpret_cast<const uint32_t*>(&op.f32_imm);
        std::stringstream ss;
        ss << "float32::from_bits(u32:0x" << std::hex << bits << ")";
        expr = ss.str();
        break;
      }
      case OpKind::kCmpOGT:
        if (op.inputs.size() >= 2) {
          expr = "float32::gt_2(" + value_map[op.inputs[0]] + ", " +
                 value_map[op.inputs[1]] + ")";
        }
        break;
      case OpKind::kSelect:
        if (op.inputs.size() >= 3) {
          expr = "if (" + value_map[op.inputs[0]] + ") { (" +
                 value_map[op.inputs[1]] + ") } else { (" + value_map[op.inputs[2]] + ") }";
        }
        break;
      default:
        return failure();
    }

    if (expr.empty()) {
      return failure();
    }

    let_statements.push_back(DslxStmt::MakeLet(result_name, "F32", expr));
    value_map[op.result] = result_name;
  }

  if (!region.yields.empty()) {
    auto it = value_map.find(region.yields[0]);
    if (it != value_map.end()) {
      return std::make_pair(std::move(let_statements), it->second);
    }
  }

  return failure();
}

}  // namespace mlir::xls
