// Copyright 2025 The XLS Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "xls/contrib/mlir/transforms/linalg/dslx_codegen.h"
#include "xls/contrib/mlir/transforms/linalg/linalg_config.h"

#include <algorithm>
#include <cstdint>
#include <sstream>
#include <string>
#include <vector>

#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/Support/LogicalResult.h"
#include "xls/contrib/mlir/transforms/linalg/linalg_types.h"
#include "xls/contrib/mlir/transforms/linalg/linalg_eval.h"
#include "xls/contrib/mlir/transforms/linalg/schedule_gen.h"
#include "xls/contrib/mlir/transforms/linalg/unroll_plan_gen.h"
#include "xls/contrib/mlir/transforms/linalg/reduction_utils.h"

#include "absl/strings/str_cat.h"
#include "absl/strings/str_join.h"

namespace mlir::xls {

// DslxEmissionContext implementation
std::string DslxEmissionContext::indent() const {
  return std::string(indent_level * 2, ' ');
}

void DslxEmissionContext::increase_indent() {
  indent_level++;
}

void DslxEmissionContext::decrease_indent() {
  if (indent_level > 0) {
    indent_level--;
  }
}

// DslxCodegen implementation
DslxCodegen::DslxCodegen(std::ostream& output) : output_(output) {}

mlir::LogicalResult DslxCodegen::EmitFunction(const LinalgGeneric& g,
                                             const BroadcastAnalysis& A,
                                             const Schedule& sch,
                                             const UnrollPlan& up,
                                             const ReduceCtx& rctx,
                                             const CodegenConfig& config,
                                             const DslxEmissionContext& ctx) {
  // Emit function header with parameters and return type
  if (EmitFunctionHeader(g, A, ctx).failed()) {
    return mlir::failure();
  }
  
  // Emit zero initializations for output tensors
  if (EmitZeroInits(g, A, ctx).failed()) {
    return mlir::failure();
  }
  
  // Emit nested loop structure with unrolling
  if (EmitLoops(g, A, sch, up, rctx, config, ctx).failed()) {
    return mlir::failure();
  }
  
  // Emit return statement
  output_ << ctx.indent() << "result\n";
  output_ << "}\n";
  
  return mlir::success();
}

mlir::LogicalResult DslxCodegen::EmitFunctionHeader(const LinalgGeneric& g,
                                                   const BroadcastAnalysis& A,
                                                   const DslxEmissionContext& ctx) {
  output_ << "// Generated by dslx_codegen from MLIR Linalg operation\n";
  output_ << "// DO NOT EDIT - This file is auto-generated\n\n";
  output_ << "#![feature(type_inference_v2)]\n\n";
  output_ << "import float32;\n\n";
  output_ << "type F32 = float32::F32;\n\n";
  output_ << "fn " << ctx.function_name << "(";
  
  // Emit input parameters (non-output operands)
  std::vector<std::string> params;
  for (const auto& operand : g.operands) {
    if (!operand.is_output) {
      std::string param_type = GetOperandType(operand, A);
      params.push_back(absl::StrCat(operand.name, ": ", param_type));
    }
  }
  
  output_ << absl::StrJoin(params, ", ");
  output_ << ") -> " << GetReturnType(g, A) << " {\n";
  
  return mlir::success();
}

mlir::LogicalResult DslxCodegen::EmitZeroInits(const LinalgGeneric& g,
                                              const BroadcastAnalysis& A,
                                              const DslxEmissionContext& ctx) {
  // Find and initialize output operands
  for (const auto& operand : g.operands) {
    if (operand.is_output) {
      // Get output shape (only parallel dimensions)
      std::vector<int64_t> output_shape;
      for (int i = 0; i < operand.type.shape.size(); ++i) {
        const auto& map_result = operand.map.results[i];
        if (map_result.kind == AffineExpr::kVar) {
          int dim_id = map_result.var;
          if (dim_id < g.dims.size() && g.dims[dim_id].kind == IterKind::kParallel) {
            output_shape.push_back(operand.type.shape[i]);
          }
        }
      }
      
      // Emit zero tensor initialization
      std::string zero_tensor = BuildZeroTensor(output_shape, ctx);
      output_ << ctx.indent() << "let " << operand.name << " = " << zero_tensor << ";\n";
    }
  }
  
  return mlir::success();
}

mlir::LogicalResult DslxCodegen::EmitLoops(const LinalgGeneric& g,
                                          const BroadcastAnalysis& A,
                                          const Schedule& sch,
                                          const UnrollPlan& up,
                                          const ReduceCtx& rctx,
                                          const CodegenConfig& config,
                                          const DslxEmissionContext& ctx) {
  if (sch.bands.empty()) {
    return mlir::failure();
  }
  
  const auto& band = sch.bands[0];
  
  // Find the output operand name to use as initial value
  std::string initial_value = "output0";  // Default fallback
  for (const auto& operand : g.operands) {
    if (operand.is_output) {
      initial_value = operand.name;
      break;
    }
  }
  
  // Separate parallel and reduction loops
  std::vector<const LoopBand::Loop*> parallel_loops, reduction_loops;
  for (const auto& loop : band.loops) {
    if (g.dims[loop.dim].kind == IterKind::kParallel) {
      parallel_loops.push_back(&loop);
    } else {
      reduction_loops.push_back(&loop);
    }
  }
  
  // Emit the main nested loop structure
  std::string result_var = initial_value;
  
  // Emit parallel loops (outer) with tiling support
  for (size_t i = 0; i < parallel_loops.size(); ++i) {
    const auto& loop = *parallel_loops[i];
    std::string loop_var = "result" + std::to_string(i + 1);
    
    // Check if this dimension should be tiled
    int tile_size = config.tile_size(i);
    bool should_tile = (tile_size > 1 && tile_size < loop.end);
    
    if (should_tile) {
      // Emit tile-outer loop
      std::string tile_outer_var = "Do_" + std::to_string(loop.dim);
      
      output_ << ctx.indent() << "let " << loop_var << " = for (" << tile_outer_var 
              << ", Oacc) : (u32, " << GetReturnType(g, A) << ") in u32:0.." 
              << loop.end << " step " << tile_size << " {\n";
      
      DslxEmissionContext tile_ctx = ctx;
      tile_ctx.increase_indent();
      
      // Calculate tile end with proper boundary handling
      std::string tile_end_expr = "min(u32:" + tile_outer_var + " + u32:" + std::to_string(tile_size) + ", u32:" + std::to_string(loop.end) + ")";
      
      // Emit tile-inner loop with proper bounds
      std::string tile_inner_var = "i" + std::to_string(loop.dim);
      output_ << tile_ctx.indent() << "let tile_result = for (" << tile_inner_var 
              << ", tile_acc) : (u32, " << GetReturnType(g, A) << ") in u32:" 
              << tile_outer_var << ".." << tile_end_expr << " {\n";
      
      DslxEmissionContext inner_ctx = tile_ctx;
      inner_ctx.increase_indent();
      
      // If this is the last parallel loop and we have reduction loops, emit reduction logic
      if (i == parallel_loops.size() - 1 && !reduction_loops.empty()) {
        if (EmitPerElementReductionLoops(g, A, reduction_loops, rctx, config, inner_ctx).failed()) {
          return mlir::failure();
        }
      } else {
        // Simple pass-through for intermediate parallel loops
        output_ << inner_ctx.indent() << "tile_acc\n";
      }
      
      output_ << tile_ctx.indent() << "}(tile_acc);\n";
      output_ << tile_ctx.indent() << "tile_result\n";
      output_ << ctx.indent() << "}(" << result_var << ");\n";
    } else {
      // Emit regular loop (no tiling)
      output_ << ctx.indent() << "let " << loop_var << " = for (i" << loop.dim 
              << ", Oacc) : (u32, " << GetReturnType(g, A) << ") in u32:0.." 
              << loop.end << " {\n";
      
      DslxEmissionContext inner_ctx = ctx;
      inner_ctx.increase_indent();
      
      // If this is the last parallel loop and we have reduction loops, emit reduction logic
      if (i == parallel_loops.size() - 1 && !reduction_loops.empty()) {
        if (EmitPerElementReductionLoops(g, A, reduction_loops, rctx, config, inner_ctx).failed()) {
          return mlir::failure();
        }
      } else {
        // Simple pass-through for intermediate parallel loops
        output_ << inner_ctx.indent() << "Oacc\n";
      }
      
      output_ << ctx.indent() << "}(" << result_var << ");\n";
    }
    
    result_var = loop_var;
  }
  
  // If no parallel loops, emit reduction loops directly
      if (parallel_loops.empty() && !reduction_loops.empty()) {
      if (EmitPerElementReductionLoops(g, A, reduction_loops, rctx, config, ctx).failed()) {
        return mlir::failure();
      }
    }
  
  // Return the final result
  output_ << ctx.indent() << result_var << "\n";
  
  return mlir::success();
}

mlir::LogicalResult DslxCodegen::EmitUnrolledLoop(const LinalgGeneric& g,
                                                 const BroadcastAnalysis& A,
                                                 const LanePlan& lane_plan,
                                                 const ReduceCtx& rctx,
                                                 const DslxEmissionContext& ctx) {
  output_ << ctx.indent() << "// Unrolled loop for dimension " << lane_plan.dim 
          << " with " << lane_plan.lanes << " lanes\n";
  
  // Emit main iterations with parallel lanes
  if (lane_plan.main_iters > 0) {
    output_ << ctx.indent() << "let result = for (b, result) : (u32, " 
            << GetReturnType(g, A) << ") in u32:0.." << lane_plan.main_iters << " {\n";
    
    DslxEmissionContext inner_ctx = ctx;
    inner_ctx.increase_indent();
    
    // Emit base calculation for lane indexing
    output_ << inner_ctx.indent() << "let base = b * " << lane_plan.lanes << ";\n";
    
    // Emit parallel lanes (structural unroll)
    for (int u = 0; u < lane_plan.lanes; ++u) {
      output_ << inner_ctx.indent() << "let y" << u << " = // BODY(base + " << u << ");\n";
    }
    
    // Emit lane combination based on reduction policy
    if (EmitAccumulatorLogic(rctx, inner_ctx).failed()) {
      return mlir::failure();
    }
    
    output_ << inner_ctx.indent() << "result\n";
    output_ << ctx.indent() << "}(result);\n";
  }
  
  // Emit tail loop if needed
  if (lane_plan.has_tail) {
    output_ << ctx.indent() << "let result = for (t, result) : (u32, " 
            << GetReturnType(g, A) << ") in u32:0.." << lane_plan.tail << " {\n";
    
    DslxEmissionContext inner_ctx = ctx;
    inner_ctx.increase_indent();
    
    output_ << inner_ctx.indent() << "let base = " << lane_plan.main_iters << " * " 
            << lane_plan.lanes << ";\n";
    output_ << inner_ctx.indent() << "let y = // BODY(base + t);\n";
    output_ << inner_ctx.indent() << "// combine_scalar(y) into accumulator\n";
    output_ << inner_ctx.indent() << "result\n";
    
    output_ << ctx.indent() << "}(result);\n";
  }
  
  return mlir::success();
}

mlir::LogicalResult DslxCodegen::EmitReductionLoops(const LinalgGeneric& g,
                                                   const BroadcastAnalysis& A,
                                                   const std::vector<const LoopBand::Loop*>& reduction_loops,
                                                   const ReduceCtx& rctx,
                                                   const DslxEmissionContext& ctx) {
  // For now, emit a simple reduction accumulator
  output_ << ctx.indent() << "// Reduction accumulator (serial or (acc,c) for Kahan)\n";
  output_ << ctx.indent() << "let acc0 = float32::zero(false);\n";
  
  // Emit nested reduction loops
  std::string acc_var = "acc0";
  for (size_t i = 0; i < reduction_loops.size(); ++i) {
    const auto& loop = *reduction_loops[i];
    std::string loop_var = "acc" + std::to_string(i + 1);
    
    output_ << ctx.indent() << "let " << loop_var << " = for (i" << loop.dim 
            << ", acc) : (u32, F32) in u32:0.." << loop.end << " {\n";
    
    DslxEmissionContext inner_ctx = ctx;
    inner_ctx.increase_indent();
    
    // Emit the actual reduction body (simplified for now)
    output_ << inner_ctx.indent() << "// Reduction body for dimension " << loop.dim << "\n";
    output_ << inner_ctx.indent() << "acc + float32::zero(false)  // TODO: actual reduction logic\n";
    
    output_ << ctx.indent() << "}(" << acc_var << ");\n";
    acc_var = loop_var;
  }
  
  // Return the final accumulator value
  output_ << ctx.indent() << acc_var << "\n";
  
  return mlir::success();
}

mlir::LogicalResult DslxCodegen::EmitPerElementReductionLoops(const LinalgGeneric& g,
                                                               const BroadcastAnalysis& A,
                                                               const std::vector<const LoopBand::Loop*>& reduction_loops,
                                                               const ReduceCtx& rctx,
                                                               const CodegenConfig& config,
                                                               const DslxEmissionContext& ctx) {
  // Calculate tile dimensions for current tile
  std::vector<int> tile_sizes;
  std::vector<std::string> tile_outer_vars;
  std::vector<std::string> tile_end_exprs;
  std::vector<int> parallel_dim_indices;
  
  // Find parallel dimensions and their tile sizes
  for (size_t i = 0; i < g.dims.size(); ++i) {
    if (g.dims[i].kind == IterKind::kParallel) {
      int tile_size = config.tile_size(i);
      tile_sizes.push_back(tile_size);
      tile_outer_vars.push_back("Do_" + std::to_string(i));
      parallel_dim_indices.push_back(i);
      
      // Calculate effective tile end for this dimension
      std::string tile_end = "min(u32:Do_" + std::to_string(i) + " + u32:" + std::to_string(tile_size) + ", u32:" + std::to_string(g.dims[i].extent) + ")";
      tile_end_exprs.push_back(tile_end);
    }
  }
  
  // Calculate effective tile sizes (for partial tiles)
  std::vector<std::string> effective_tile_sizes;
  for (size_t i = 0; i < tile_outer_vars.size(); ++i) {
    effective_tile_sizes.push_back(tile_end_exprs[i] + " - " + tile_outer_vars[i]);
  }
  
  // Allocate tile-local accumulator array based on effective tile size
  if (tile_sizes.size() == 1) {
    // 1D tile - use effective tile size
    output_ << ctx.indent() << "// Allocate tile-local 1D accumulator array\n";
    output_ << ctx.indent() << "let acc_tile = F32[" << tile_sizes[0] << "]:[float32::zero(false), ...];\n";
  } else if (tile_sizes.size() == 2) {
    // 2D tile - use effective tile sizes
    output_ << ctx.indent() << "// Allocate tile-local 2D accumulator array\n";
    output_ << ctx.indent() << "let acc_tile = F32[" << tile_sizes[0] << "][" << tile_sizes[1] << "]:[[float32::zero(false), ...], ...];\n";
  } else {
    // Higher dimensional tiles - for now, use 1D flattened
    int total_size = 1;
    for (int size : tile_sizes) {
      total_size *= size;
    }
    output_ << ctx.indent() << "// Allocate tile-local flattened accumulator array\n";
    output_ << ctx.indent() << "let acc_tile = F32[" << total_size << "]:[float32::zero(false), ...];\n";
  }
  
  // Emit nested reduction loops
  std::string acc_var = "acc_tile";
  for (size_t i = 0; i < reduction_loops.size(); ++i) {
    const auto& loop = *reduction_loops[i];
    std::string loop_var = "acc" + std::to_string(i + 1);
    
    output_ << ctx.indent() << "let " << loop_var << " = for (i" << loop.dim 
            << ", acc) : (u32, " << GetAccumulatorType(tile_sizes) << ") in u32:0.." << loop.end << " {\n";
    
    DslxEmissionContext inner_ctx = ctx;
    inner_ctx.increase_indent();
    
    // Emit the reduction body with per-element accumulator updates
    output_ << inner_ctx.indent() << "// Reduction body for dimension " << loop.dim << "\n";
    if (EmitPerElementReductionBody(g, A, tile_sizes, tile_outer_vars, rctx, inner_ctx).failed()) {
      return mlir::failure();
    }
    
    output_ << ctx.indent() << "}(" << acc_var << ");\n";
    acc_var = loop_var;
  }
  
  // Write back accumulators to output tensor
  if (EmitAccumulatorWriteback(g, A, tile_sizes, tile_outer_vars, effective_tile_sizes, acc_var, config, ctx).failed()) {
    return mlir::failure();
  }
  
  return mlir::success();
}

mlir::LogicalResult DslxCodegen::EmitAccumulatorLogic(const ReduceCtx& rctx,
                                                     const DslxEmissionContext& ctx) {
  switch (rctx.policy) {
    case ReducePolicy::kSerial: {
      // Serial reduction: sum all lane values
      output_ << ctx.indent() << "let sumU = ";
      for (int u = 0; u < 6; ++u) {  // Assuming max 6 lanes for now
        if (u > 0) output_ << " + ";
        output_ << "y" << u;
      }
      output_ << ";\n";
      output_ << ctx.indent() << "let acc_next = acc + sumU;\n";
      break;
    }
    case ReducePolicy::kTree: {
      // Tree reduction: balanced binary tree
      output_ << ctx.indent() << "let sumU = ((y0 + y1) + (y2 + y3)) + (y4 + y5);\n";
      output_ << ctx.indent() << "let acc_next = acc + sumU;\n";
      break;
    }
    case ReducePolicy::kKahan: {
      // Kahan summation for numerical stability
      output_ << ctx.indent() << "// Kahan summation for lanes\n";
      output_ << ctx.indent() << "let sumU = y0 + y1 + y2 + y3 + y4 + y5;\n";
      output_ << ctx.indent() << "let acc_next = acc + sumU;\n";
      break;
    }
  }
  
  return mlir::success();
}

mlir::LogicalResult DslxCodegen::EmitPerElementReductionBody(const LinalgGeneric& g,
                                                             const BroadcastAnalysis& A,
                                                             const std::vector<int>& tile_sizes,
                                                             const std::vector<std::string>& tile_outer_vars,
                                                             const ReduceCtx& rctx,
                                                             const DslxEmissionContext& ctx) {
  // Calculate local indices within the tile
  std::vector<std::string> local_indices;
  for (size_t i = 0; i < tile_outer_vars.size(); ++i) {
    std::string local_var = "ii_" + std::to_string(i);
    local_indices.push_back(local_var);
    output_ << ctx.indent() << "let " << local_var << " = i" << i << " - " << tile_outer_vars[i] << ";\n";
  }
  
  // Emit the reduction computation
  output_ << ctx.indent() << "// Compute reduction value\n";
  output_ << ctx.indent() << "let y = float32::zero(false);  // TODO: actual computation\n";
  
  // Update the correct accumulator element
  if (tile_sizes.size() == 1) {
    // 1D tile
    output_ << ctx.indent() << "let acc_updated = update(acc, " << local_indices[0] << ", acc[" << local_indices[0] << "] + y);\n";
  } else if (tile_sizes.size() == 2) {
    // 2D tile
    output_ << ctx.indent() << "let acc_updated = update(acc, (" << local_indices[0] << ", " << local_indices[1] << "), acc[" << local_indices[0] << "][" << local_indices[1] << "] + y);\n";
  } else {
    // Higher dimensional - use flattened index
    output_ << ctx.indent() << "let flat_idx = ";
    for (size_t i = 0; i < local_indices.size(); ++i) {
      if (i > 0) output_ << " + ";
      output_ << local_indices[i] << " * " << tile_sizes[i];
    }
    output_ << ";\n";
    output_ << ctx.indent() << "let acc_updated = update(acc, flat_idx, acc[flat_idx] + y);\n";
  }
  
  output_ << ctx.indent() << "acc_updated\n";
  
  return mlir::success();
}

mlir::LogicalResult DslxCodegen::EmitAccumulatorWriteback(const LinalgGeneric& g,
                                                           const BroadcastAnalysis& A,
                                                           const std::vector<int>& tile_sizes,
                                                           const std::vector<std::string>& tile_outer_vars,
                                                           const std::vector<std::string>& effective_tile_sizes,
                                                           const std::string& acc_var,
                                                           const CodegenConfig& config,
                                                           const DslxEmissionContext& ctx) {
  // Write back accumulators to the output tensor
  output_ << ctx.indent() << "// Write back tile accumulators to output tensor\n";
  
  if (tile_sizes.size() == 1) {
    // 1D tile - single update loop with effective tile size
    output_ << ctx.indent() << "let result_updated = for (ii, result_acc) : (u32, " << GetReturnType(g, A) << ") in u32:0.." << effective_tile_sizes[0] << " (tile_acc) {\n";
    DslxEmissionContext inner_ctx = ctx;
    inner_ctx.increase_indent();
    output_ << inner_ctx.indent() << "let global_idx = " << tile_outer_vars[0] << " + ii;\n";
    output_ << inner_ctx.indent() << "update(result_acc, global_idx, acc_tile[ii])\n";
    output_ << ctx.indent() << "}(tile_acc);\n";
  } else if (tile_sizes.size() == 2) {
    // 2D tile - two nested update loops with effective tile sizes
    output_ << ctx.indent() << "let result_updated = for (ii, O_tmp1) : (u32, " << GetReturnType(g, A) << ") in u32:0.." << effective_tile_sizes[0] << " (tile_acc) {\n";
    DslxEmissionContext inner_ctx = ctx;
    inner_ctx.increase_indent();
    output_ << inner_ctx.indent() << "let row = for (kk, row_acc) : (u32, " << GetReturnType(g, A) << ") in u32:0.." << effective_tile_sizes[1] << " (O_tmp1) {\n";
    DslxEmissionContext inner_inner_ctx = inner_ctx;
    inner_inner_ctx.increase_indent();
    output_ << inner_inner_ctx.indent() << "let val = acc_tile[ii][kk];\n";
    output_ << inner_inner_ctx.indent() << "let global_i = " << tile_outer_vars[0] << " + ii;\n";
    output_ << inner_inner_ctx.indent() << "let global_k = " << tile_outer_vars[1] << " + kk;\n";
    output_ << inner_inner_ctx.indent() << "update(row_acc, global_k, val)\n";
    output_ << inner_ctx.indent() << "}(O_tmp1);\n";
    output_ << inner_ctx.indent() << "update(O_tmp1, global_i, row)\n";
    output_ << ctx.indent() << "}(tile_acc);\n";
  } else {
    // Higher dimensional - simplified for now
    output_ << ctx.indent() << "// TODO: Implement writeback for higher dimensional tiles\n";
    output_ << ctx.indent() << "tile_acc\n";
  }
  
  return mlir::success();
}

std::string DslxCodegen::GetAccumulatorType(const std::vector<int>& tile_sizes) {
  if (tile_sizes.size() == 1) {
    return "F32[" + std::to_string(tile_sizes[0]) + "]";
  } else if (tile_sizes.size() == 2) {
    return "F32[" + std::to_string(tile_sizes[0]) + "][" + std::to_string(tile_sizes[1]) + "]";
  } else {
    // Flattened for higher dimensions
    int total_size = 1;
    for (int size : tile_sizes) {
      total_size *= size;
    }
    return "F32[" + std::to_string(total_size) + "]";
  }
}

std::string DslxCodegen::GetOperandType(const Operand& operand, const BroadcastAnalysis& A) {
  // Check if it's a scalar (rank 0 or all 1s)
  bool is_scalar = true;
  for (int64_t dim : operand.type.shape) {
    if (dim != 1) {
      is_scalar = false;
      break;
    }
  }
  
  if (is_scalar) {
    return "F32";
  }
  
  // Build tensor type with dimensions
  std::vector<std::string> dims;
  for (int64_t dim : operand.type.shape) {
    dims.push_back(std::to_string(dim));
  }
  
  return absl::StrCat("F32[", absl::StrJoin(dims, "]["), "]");
}

std::string DslxCodegen::GetReturnType(const LinalgGeneric& g, const BroadcastAnalysis& A) {
  // Find output operands and build return type
  std::vector<std::string> output_types;
  for (const auto& operand : g.operands) {
    if (operand.is_output) {
      // For function returns, we need to use 1D arrays (multi-dimensional return types don't work)
      // Calculate total size for 1D array
      int64_t total_size = 1;
      for (int64_t dim : operand.type.shape) {
        total_size *= dim;
      }
      output_types.push_back(absl::StrCat("F32[", total_size, "]"));
    }
  }
  
  if (output_types.empty()) {
    return "()";
  } else if (output_types.size() == 1) {
    return output_types[0];
  } else {
    return absl::StrCat("(", absl::StrJoin(output_types, ", "), ")");
  }
}

std::string DslxCodegen::BuildZeroTensor(const std::vector<int64_t>& shape,
                                        const DslxEmissionContext& ctx) {
  if (shape.empty()) {
    return "float32::zero(false)";
  }
  
  if (shape.size() == 1) {
    // 1D zero vector
    return absl::StrCat("F32[", shape[0], "]:[float32::zero(false), ...]");
  }
  
  // For function returns, we need to flatten multi-dimensional arrays to 1D
  // Calculate total size
  int64_t total_size = 1;
  for (int64_t dim : shape) {
    total_size *= dim;
  }
  
  // Return 1D array with total size
  return absl::StrCat("F32[", total_size, "]:[float32::zero(false), ...]");
}

std::string DslxCodegen::EmitUpdateCall(const std::string& tensor_name,
                                       const std::string& indices,
                                       const std::string& value) {
  return absl::StrCat("update(", tensor_name, ", ", indices, ", ", value, ")");
}

mlir::LogicalResult DslxCodegen::EmitFunction(const LinalgGeneric& g,
                                             const BroadcastAnalysis& A,
                                             const Schedule& sch,
                                             const UnrollPlan& up) {
  DslxEmissionContext ctx;
  ctx.function_name = "complex_reduction_example";

  ReduceCtx rctx;
  rctx.policy = GetLinalgCodegenConfig().reduce_policy();
  rctx.tree_fan_in = 2;
  rctx.deterministic = true;

  return EmitFunction(g, A, sch, up, rctx, GetLinalgCodegenConfig(), ctx);
}

}  // namespace mlir::xls

